# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import routir_pb2 as routir__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in routir_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RoutirStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/routir.v1.Routir/Ping',
                request_serializer=routir__pb2.PingRequest.SerializeToString,
                response_deserializer=routir__pb2.PingResponse.FromString,
                _registered_method=True)
        self.Avail = channel.unary_unary(
                '/routir.v1.Routir/Avail',
                request_serializer=routir__pb2.AvailRequest.SerializeToString,
                response_deserializer=routir__pb2.AvailResponse.FromString,
                _registered_method=True)
        self.Search = channel.unary_unary(
                '/routir.v1.Routir/Search',
                request_serializer=routir__pb2.SearchRequest.SerializeToString,
                response_deserializer=routir__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.Score = channel.unary_unary(
                '/routir.v1.Routir/Score',
                request_serializer=routir__pb2.ScoreRequest.SerializeToString,
                response_deserializer=routir__pb2.ScoreResponse.FromString,
                _registered_method=True)
        self.Content = channel.unary_unary(
                '/routir.v1.Routir/Content',
                request_serializer=routir__pb2.ContentRequest.SerializeToString,
                response_deserializer=routir__pb2.ContentResponse.FromString,
                _registered_method=True)
        self.Pipeline = channel.unary_unary(
                '/routir.v1.Routir/Pipeline',
                request_serializer=routir__pb2.PipelineRequest.SerializeToString,
                response_deserializer=routir__pb2.PipelineResponse.FromString,
                _registered_method=True)


class RoutirServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Avail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Score(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Content(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Pipeline(self, request, context):
        """RPC slots reserved for v2 streaming -- do not implement now:
        rpc ScoreStream(stream ScoreChunk) returns (stream ScoreResult);
        rpc PipelineStream(PipelineRequest) returns (stream PipelineResponse);
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RoutirServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=routir__pb2.PingRequest.FromString,
                    response_serializer=routir__pb2.PingResponse.SerializeToString,
            ),
            'Avail': grpc.unary_unary_rpc_method_handler(
                    servicer.Avail,
                    request_deserializer=routir__pb2.AvailRequest.FromString,
                    response_serializer=routir__pb2.AvailResponse.SerializeToString,
            ),
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=routir__pb2.SearchRequest.FromString,
                    response_serializer=routir__pb2.SearchResponse.SerializeToString,
            ),
            'Score': grpc.unary_unary_rpc_method_handler(
                    servicer.Score,
                    request_deserializer=routir__pb2.ScoreRequest.FromString,
                    response_serializer=routir__pb2.ScoreResponse.SerializeToString,
            ),
            'Content': grpc.unary_unary_rpc_method_handler(
                    servicer.Content,
                    request_deserializer=routir__pb2.ContentRequest.FromString,
                    response_serializer=routir__pb2.ContentResponse.SerializeToString,
            ),
            'Pipeline': grpc.unary_unary_rpc_method_handler(
                    servicer.Pipeline,
                    request_deserializer=routir__pb2.PipelineRequest.FromString,
                    response_serializer=routir__pb2.PipelineResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'routir.v1.Routir', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('routir.v1.Routir', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Routir(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/routir.v1.Routir/Ping',
            routir__pb2.PingRequest.SerializeToString,
            routir__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Avail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/routir.v1.Routir/Avail',
            routir__pb2.AvailRequest.SerializeToString,
            routir__pb2.AvailResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/routir.v1.Routir/Search',
            routir__pb2.SearchRequest.SerializeToString,
            routir__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Score(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/routir.v1.Routir/Score',
            routir__pb2.ScoreRequest.SerializeToString,
            routir__pb2.ScoreResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Content(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/routir.v1.Routir/Content',
            routir__pb2.ContentRequest.SerializeToString,
            routir__pb2.ContentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Pipeline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/routir.v1.Routir/Pipeline',
            routir__pb2.PipelineRequest.SerializeToString,
            routir__pb2.PipelineResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
